name: Dev Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install deps
      run: pnpm install

    - name: Lint
      run: pnpm run lint || true

    - name: Build
      run: pnpm run build

    - name: Deploy (e.g. to Render/VPS)
      run: ./deploy.sh  # или rsync/docker/scp etc.
